name: Deploy content to Pages

on:
  push:
    branches: ["table"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ ! endsWith(github.actor, '[bot]') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get markdown files
        run: |
          {
            echo 'FILELIST<<EOF'
            find . -name '*.md' -print 
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Pages to HTML
        run: |
          echo "" > html/index.html
          IFS=''
          for i in $FILELIST; do
             tr '\n' '\<br \/\>' < $i >> html/index.html
          done 
      - name: Commit HTML to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add html/index.html
          git commit -m "Built HTML file"
          git push
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
