name: Deploy content to Pages

on:
  push:
    branches: ["table"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ ! endsWith(github.actor, '[bot]') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Markdown files to HTML
        run: |
          FILELIST=$(ls -1 *.md)
          cat html/header.html > html/index.html
          for i in $FILELIST; do
              IFS=''
              touch html/temp.html
              cat $i > html/temp.html
              # Heading 3
              echo "$(sed -r 's/^\#\#\# (.*)$/\<h3\>\1\<\/h3\>/' html/temp.html)" > html/temp.html
              # Heading 2
              echo "$(sed -r 's/^\#\# (.*)$/\<h2\>\1\<\/h2\>/' html/temp.html)" > html/temp.html
              # Heading 1
              echo "$(sed -r 's/^\# (.*)$/\<h1\>\1\<\/h1\>/' html/temp.html)" > html/temp.html
              # Bold text
              echo "$(sed -r 's/\*\*(.*)\*\*/\<b\>\1\<\/b\>/' html/temp.html)" > html/temp.html
              # Italic text
              echo "$(sed -r 's/\*(.*)\*/\<i\>\1\<\/i\>/' html/temp.html)" > html/temp.html
              # Italic text
              echo "$(sed -r 's/\_(.*)\_/\<i\>\1\<\/i\>/' html/temp.html)" > html/temp.html
              # Links
              echo "$(sed -r 's/\[(.*)\]\((.*)\)/\<a href=\"\2\"\>\1\<\/a\>/' html/temp.html)" > html/temp.html
              # Line breaks
              echo "$(sed -r 's/$/<br\/>/' html/temp.html)" > html/temp.html
              cat html/temp.html >> html/index.html
          done
          cat html/footer.html >> html/index.html
          cat html/index.html
      - name: Commit HTML to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add html/index.html
          git commit -m "Built HTML file"
          git push
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
